version: '3.9'

networks:
  laravel-network:
    name: laravel-network
    driver: bridge

services:
  laravel-laravel:
    platform: 'linux/amd64'
    container_name: laravel-php
    build:
      context: ./docker/laravel-php
      dockerfile: Dockerfile
      args:
        WWWGROUP: 1000
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '80:80'
    environment:
      TZ: Europe/Warsaw
      WWWUSER: 1000
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - '.:/var/www/html'
    networks:
      - laravel-network
    depends_on:
      - laravel-mysql
    healthcheck:
      test: [ "CMD", "php", "-v" ]
      retries: 3
      timeout: 5s

  laravel-mysql:
    platform: 'linux/amd64'
    container_name: laravel-mysql
    image: 'mysql:8.0.30'
    env_file: .env
    ports:
      - '33066:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: Europe/Warsaw
    cap_add:
      - SYS_NICE
    volumes:
      - ./docker/laravel-mysql/:/docker-entrypoint-initdb.d
      - '${DOCKER_MYSQL_VOLUME}:/var/lib/mysql'
    networks:
      - laravel-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
    command: [ "--innodb_redo_log_capacity=1G" ]

  laravel-redis:
    platform: 'linux/amd64'
    environment:
      TZ: Europe/Warsaw
    container_name: laravel-redis
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-63799}:6379'
    volumes:
      - 'laravel-redis:/data'
    networks:
      - laravel-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

volumes:
  laravel-mysql:
    name: laravel-mysql
    driver: local
  laravel-redis:
    name: laravel-redis
    driver: local
